/*
 * This Spock specification was generated by the Gradle 'init' task.
 */
import spock.lang.Specification

class UserImporterGroovyTest extends Specification {
    def "someLibraryMethod returns true"() {
        setup:
        def importer = new UserImporterGroovy()

        when:
        def result = true // importer.doThings()

        then:
        result == true
    }
}
